import { GroupSummary, Student } from "./types/types";

// Time slots definition
export const TIME_SLOTS = [
    { id: 1, time: "08:30 - 10:00" },
    { id: 2, time: "10:10 - 11:40" },
    { id: 3, time: "12:10 - 13:40" },
    { id: 4, time: "13:50 - 15:20" },
    { id: 5, time: "15:30 - 17:00" },
    { id: 6, time: "17:10 - 18:40" },
];

export const ALL_SUBJECTS = [
    "Web Development",
    "Database Design",
    "Network Security",
    "Algorithms",
    "Operating Systems",
    "Cyber Security",
    "Linear Algebra",
    "Thesis Project",
];

// Generate 36 days of mock data columns (2 pages worth)
export const JOURNAL_DAYS = Array.from(
    { length: 36 },
    (_, i) => `Oct ${i + 1}`,
);

export const MOCK_STUDENTS: Student[] = [
    {
        id: "1",
        name: "Ivanov A.",
        grades: [
            5,
            4,
            5,
            null,
            3,
            4,
            5,
            5,
            4,
            null,
            3,
            4,
            5,
            2,
            4,
            5,
            5,
            4,
            5,
            4,
            5,
            null,
            3,
            4,
            5,
            5,
            4,
            null,
            3,
            4,
            5,
            2,
            4,
            5,
            5,
            4,
        ],
        attendance: [
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
    },
    {
        id: "2",
        name: "Petrov B.",
        grades: [
            3,
            3,
            4,
            4,
            null,
            3,
            3,
            4,
            5,
            5,
            null,
            3,
            2,
            3,
            4,
            3,
            4,
            4,
            3,
            3,
            4,
            4,
            null,
            3,
            3,
            4,
            5,
            5,
            null,
            3,
            2,
            3,
            4,
            3,
            4,
            4,
        ],
        attendance: [
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
    },
    {
        id: "3",
        name: "Sidorov C.",
        grades: Array(36).fill(5),
        attendance: Array(36).fill(true),
    },
    {
        id: "4",
        name: "Smirnova D.",
        grades: Array(36).fill(4),
        attendance: Array(36).fill(true),
    },
    {
        id: "5",
        name: "Volkov E.",
        grades: Array(36).fill(5),
        attendance: Array(36).fill(true),
    },
    {
        id: "6",
        name: "Kuznetsov F.",
        grades: Array(36).fill(3),
        attendance: Array(36).fill(true),
    },
    {
        id: "7",
        name: "Popov G.",
        grades: Array(36).fill(4),
        attendance: Array(36).fill(true),
    },
    {
        id: "8",
        name: "Sokolov H.",
        grades: Array(36).fill(null),
        attendance: Array(36).fill(true),
    },
    {
        id: "9",
        name: "Sokolov H.",
        grades: Array(36).fill(null),
        attendance: Array(36).fill(true),
    },
    {
        id: "10",
        name: "Sokolov H.",
        grades: Array(36).fill(null),
        attendance: Array(36).fill(true),
    },
];

// Template for a week's schedule
export const MOCK_SCHEDULE_TEMPLATE = [
    {
        dayName: "Понедельник",
        lessons: [
            {
                id: "l1",
                subject:
                    " УП.01.01 Учебная практика по разработке модулей программного обеспечения для компьютерных систем",
                group: "IS-301",
                pairNumber: 1,
                room: "Lab 101",
            },
            {
                id: "l2",
                subject:
                    "МДК 02.02 Инструментальные средства разработки программного обеспечения ",
                group: "IS-302",
                pairNumber: 2,
                room: "Lab 204",
            },
        ],
    },
    {
        dayName: "Вторник",
        lessons: [
            {
                id: "l3",
                subject: "Network Security",
                group: "CS-201",
                pairNumber: 1,
                room: "Lec 305",
            },
            {
                id: "l4",
                subject: "Web Development",
                group: "IS-301",
                pairNumber: 3,
                room: "Lab 101",
            },
            {
                id: "l5",
                subject: "Algorithms",
                group: "CS-202",
                pairNumber: 4,
                room: "Lec 305",
            },
            {
                id: "l6",
                subject: "Algorithms",
                group: "CS-202",
                pairNumber: 5,
                room: "Lec 305",
            },
            {
                id: "l7",
                subject: "Algorithms",
                group: "CS-202",
                pairNumber: 6,
                room: "Lec 305",
            },
        ],
    },
    {
        dayName: "Среда",
        lessons: [
            {
                id: "l6",
                subject: "Database Design",
                group: "IS-302",
                pairNumber: 2,
                room: "Lab 204",
            },
        ],
    },
    {
        dayName: "Четверг",
        lessons: [
            {
                id: "l7",
                subject: "Web Development",
                group: "IS-303",
                pairNumber: 1,
                room: "Lab 101",
            },
            {
                id: "l8",
                subject: "Operating Systems",
                group: "IS-301",
                pairNumber: 2,
                room: "Lec 202",
            },
        ],
    },
    {
        dayName: "Пятница",
        lessons: [
            {
                id: "l9",
                subject: "Cyber Security",
                group: "CS-401",
                pairNumber: 3,
                room: "Lec 105",
            },
        ],
    },
    {
        dayName: "Суббота",
        lessons: [
            {
                id: "l10",
                subject: "Consultation",
                group: "All Groups",
                pairNumber: 1,
                room: "Office 12",
            },
        ],
    },
];

export const MOCK_GROUPS: GroupSummary[] = [
    {
        id: "g1",
        name: "IS-301",
        subjects: ["Web Development", "Operating Systems"],
    },
    { id: "g2", name: "IS-302", subjects: ["Database Design"] },
    {
        id: "g3",
        name: "CS-201",
        subjects: ["Network Security", "Linear Algebra"],
    },
    {
        id: "g4",
        name: "4-22 ИСП-8",
        subjects: ["Cyber Security", "Thesis Project"],
    },
];
